version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: sbStw71imn5c9ATjfPvDotgSyReJHM+il7wz8/083Xy3BONRyRxIg0cOjGAr8evI
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd src

    dotnet restore

    dotnet build -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION

    dotnet pack -c Release  /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED" --include-symbols

    #Tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -oldStyle -target:"nunit3-console.exe" -targetargs:"Tests.net45.dll" -targetdir:src\Tests.net45\bin\Release\ -output:coverage.xml -filter:"+[*Tests*]*" -searchdirs:src\Tests.net45\bin\Release\

    #tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml
artifacts:
- path: src\geschikt\bin\Release\netstandard1.0\geschikt.dll
  name: netstandard1.0
- path: src\geschikt\bin\Release\netstandard1.4\geschikt.dll
  name: netstandard1.4
- path: src\geschikt\bin\Release\net40\geschikt.dll
  name: net40
- path: src\geschikt\bin\Release\net45\geschikt.dll
  name: net45
- path: 'src\geschikt\bin\Release\*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: nuget
  on:
    branch: master