version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: src\**\AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: sbStw71imn5c9ATjfPvDotgSyReJHM+il7wz8/083Xy3BONRyRxIg0cOjGAr8evI
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: "set \"APPVEYOR_PR_BUILD=\"\nfor /f \"delims=-.0123456789\" %%i in (\"%APPVEYOR_BUILD_VERSION%\") do set APPVEYOR_PR_BUILD=%%i\ncd src\nnuget restore\ncd ..\nIF EXIST Tools RMDIR /s /q Tools\nnuget install coveralls.net -Version 0.7.0 -OutputDirectory Tools \nnuget install OpenCover -Version 4.6.519 -OutputDirectory Tools"
build:
  project: src\geschikt.sln
  verbosity: minimal
after_build:
- cmd: >-
    dir Tools\OpenCover.4.6.519\tools

    if "%APPVEYOR_PR_BUILD%"=="" CALL copynugetfiles.bat

    Tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -oldStyle -target:"nunit3-console.exe" -targetargs:"Tests.net45.dll" -targetdir:src\Tests.net45\bin\Release\ -output:coverage.xml -filter:"+[*Tests*]*" -searchdirs:src\Tests.net45\bin\Release\

    tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml
artifacts:
- path: src\geschikt\bin\Release\geschikt.dll
  name: net40-client
- path: src\geschikt.net45\bin\Release\geschikt.dll
  name: net45
- path: '*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: nuget
  on:
    branch: master